const express=require('express');
const path=require('path');
const fs=require('fs');
const crypto=require('crypto');
const app=express();
const PORT=process.env.PORT||3000;
const DATA_DIR=path.join(__dirname,'data');
const DB_FILE=path.join(DATA_DIR,'db.json');
if(!fs.existsSync(DATA_DIR))fs.mkdirSync(DATA_DIR,{recursive:true});
const PERMS={
 PLAYER:['duel.play','deck.manage','friend.manage','tournament.enter.open'],
 VIP_1:['duel.play','deck.manage','friend.manage','tournament.enter.open','tournament.enter.vip1'],
 VIP_2:['duel.play','deck.manage','friend.manage','tournament.enter.open','tournament.enter.vip1','tournament.enter.vip2'],
 VIP_3:['duel.play','deck.manage','friend.manage','tournament.enter.open','tournament.enter.vip1','tournament.enter.vip2','tournament.enter.vip3'],
 ORGANIZER:['duel.play','deck.manage','friend.manage','tournament.enter.open','tournament.create','tournament.manage'],
 JUDGE:['duel.play','deck.manage','friend.manage','tournament.enter.open','tournament.judge','audit.view'],
 ADMIN:['duel.play','deck.manage','friend.manage','tournament.enter.open','cards.use.all','cards.test','tournament.enter.all','tournament.create','tournament.manage','tournament.judge','audit.view','users.manage','admin.test'],
 SUPER_ADMIN:['duel.play','deck.manage','friend.manage','tournament.enter.open','cards.use.all','cards.test','tournament.enter.all','tournament.create','tournament.manage','tournament.judge','audit.view','users.manage','roles.manage','rewards.manage','game.config','admin.test']
};
const defaultDb={users:[],roles:PERMS,cardsOwned:{},decks:[],friends:[],tournaments:[],tournamentEntries:[],rewards:[],audit:[]};
function loadDb(){try{return JSON.parse(fs.readFileSync(DB_FILE,'utf8'))}catch{return JSON.parse(JSON.stringify(defaultDb))}}
let db=loadDb();
for(const k of Object.keys(defaultDb))if(db[k]===undefined)db[k]=JSON.parse(JSON.stringify(defaultDb[k]));
db.roles=PERMS;
function saveDb(){fs.writeFileSync(DB_FILE,JSON.stringify(db,null,2))}
const CARDS=JSON.parse(fs.readFileSync(path.join(__dirname,'cards.json'),'utf8'));
const PNJ=JSON.parse(fs.readFileSync(path.join(__dirname,'pnj.json'),'utf8'));
const sessions=new Map(),games=new Map();
const clone=x=>JSON.parse(JSON.stringify(x));
function hashPassword(password,salt=crypto.randomBytes(16).toString('hex')){const hash=crypto.scryptSync(String(password),salt,64).toString('hex');return `scrypt:${salt}:${hash}`}
function verifyPassword(password,stored){if(!stored)return false;if(stored.startsWith('scrypt:')){const [,salt,expected]=stored.split(':');const got=crypto.scryptSync(String(password),salt,64).toString('hex');return crypto.timingSafeEqual(Buffer.from(got,'hex'),Buffer.from(expected,'hex'))}return stored===crypto.createHash('sha256').update(String(password)).digest('hex')}
function audit(actor,action,resource='',details={}){db.audit.push({id:crypto.randomUUID(),actor,action,resource,details,timestamp:new Date().toISOString()});db.audit=db.audit.slice(-3000);saveDb()}
function bootstrap(){const username=process.env.ADMIN_USERNAME||'admin';const password=process.env.ADMIN_PASSWORD||'change-me-now';let changed=false;let u=db.users.find(x=>x.username===username);if(!u){u={id:crypto.randomUUID(),username,role:'SUPER_ADMIN',passwordHash:hashPassword(password),createdAt:new Date().toISOString()};db.users.push(u);changed=true;console.log(`SUPER_ADMIN créé: ${username}`)}if(db.tournaments.length===0){const seed=[['Tournoi 1 — Portail des Duellistes',0],['Tournoi 2 — Ligue VIP',1],['Tournoi 3 — Grand Conflit',2],['Tournoi 4 — Championnat des Mondes',2],['Tournoi 5 — Coupe Ultime',2]];for(let i=0;i<seed.length;i++)db.tournaments.push({id:uid(),slot:i+1,name:seed[i][0],vipRequired:seed[i][1],rewardTop5:true,status:'OPEN',createdBy:'SYSTEM',createdAt:new Date().toISOString()});changed=true}if(changed)saveDb()}
bootstrap();
app.use(express.json({limit:'1mb'}));app.use(express.static(path.join(__dirname,'public')));
function issueSession(userId){const t=crypto.randomBytes(32).toString('hex');sessions.set(t,{userId,createdAt:Date.now()});return t}
function auth(req,res,next){const t=(req.headers.authorization||'').replace(/^Bearer\s+/i,'');const s=sessions.get(t);if(!s)return res.status(401).json({error:'Authentification requise'});if(Date.now()-s.createdAt>12*60*60*1000){sessions.delete(t);return res.status(401).json({error:'Session expirée'})}const u=db.users.find(x=>x.id===s.userId);if(!u)return res.status(401).json({error:'Compte introuvable'});req.user=u;req.token=t;req.permissions=PERMS[u.role]||[];next()}
function has(req,p){return req.permissions.includes(p)}
function requirePerm(p){return (req,res,next)=>has(req,p)?next():res.status(403).json({error:'Permission refusée',permission:p})}
function uid(){return crypto.randomUUID()}
function card(id){return CARDS.find(c=>c.id===id)}
function starterCollection(){return CARDS.slice(0,Math.min(20,CARDS.length)).map(c=>c.id)}
function ownedCards(user){if(hasFakeAll(user))return CARDS.map(c=>c.id);return db.cardsOwned[user.id]||[]}
function hasFakeAll(user){return ['ADMIN','SUPER_ADMIN'].includes(user.role)}
function publicUser(u){return {id:u.id,username:u.username,role:u.role,createdAt:u.createdAt}}
function tournamentAccess(user,t){if(t.status!=='OPEN')return false;if(hasFakeAll(user))return true;if(t.vipRequired===0)return true;const rank={PLAYER:0,VIP_1:1,VIP_2:2,VIP_3:3};return (rank[user.role]||0)>=t.vipRequired}
function validateDeck(user,deck){if(!deck||!Array.isArray(deck.cards))return 'Deck invalide.';if(deck.cards.length<40||deck.cards.length>60)return 'Le Main Deck doit contenir 40 à 60 cartes.';const owned=new Set(ownedCards(user));if(!hasFakeAll(user)){const missing=deck.cards.find(id=>!owned.has(id));if(missing)return `Carte non possédée: ${missing}`}return null}
// Basic duel engine retained from V1, with server-owned state.
function shuffle(a){a=a.slice();for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function emptyPlayer(){return {lp:8000,deck:[],hand:[],grave:[],field:Array(5).fill(null),spells:Array(5).fill(null),normalUsed:false,hasBattled:false}}
function newGame(pnjId='PNJ01',deckIds=null){const p=emptyPlayer(),e=emptyPlayer();const source=(deckIds&&deckIds.length>=40?deckIds:starterCollection());const deck=shuffle(Array.from({length:40},(_,i)=>source[i%source.length]));p.deck=deck;e.deck=shuffle(deck);const g={id:uid(),turn:1,active:'player',phase:'DRAW',firstTurn:true,winner:null,log:[],player:p,enemy:e,pnj:PNJ.find(x=>x.id===pnjId)||PNJ[0]};for(let i=0;i<5;i++){p.hand.push(p.deck.shift());e.hand.push(e.deck.shift())}g.log.push('Duel commencé.');return g}
function pub(g){return {id:g.id,turn:g.turn,active:g.active,phase:g.phase,firstTurn:g.firstTurn,winner:g.winner,log:g.log.slice(-30),player:clone(g.player),enemy:{lp:g.enemy.lp,handCount:g.enemy.hand.length,deckCount:g.enemy.deck.length,graveCount:g.enemy.grave.length,field:g.enemy.field.map(x=>x?{id:x.id,name:x.name,atk:x.atk,def:x.def,pos:x.pos,face:x.face}:null)},pnj:g.pnj}}
function phaseAllowed(g,p){return g.active==='player'&&g.phase===p}
function drawOne(g,pl){if(!pl.deck.length){g.winner=pl===g.player?'enemy':'player';g.log.push('Deck vide : défaite.');return false}pl.hand.push(pl.deck.shift());return true}
function advance(g){const order=['DRAW','STANDBY','MAIN1','BATTLE','MAIN2','END'];const i=order.indexOf(g.phase);if(i<5){g.phase=order[i+1];return}g.active=g.active==='player'?'enemy':'player';if(g.active==='player')g.turn++;g.phase='DRAW';g.firstTurn=g.turn===1;const p=g.active==='player'?g.player:g.enemy;p.normalUsed=false;p.hasBattled=false;if(!g.firstTurn)drawOne(g,p);g.log.push(`Tour ${g.turn} : ${g.active==='player'?'Joueur':'PNJ'}`)}
function tributeCount(c){return c.level>=7?2:c.level>=5?1:0}
function summon(g,handIndex,zone,faceDown=false){if(!phaseAllowed(g,'MAIN1'))throw Error('Invocation en Main Phase 1 uniquement.');const p=g.player;if(p.normalUsed)throw Error('Invocation Normale déjà utilisée.');if(zone<0||zone>4||p.field[zone])throw Error('Zone Monstre occupée.');const c=card(p.hand[handIndex]);if(!c||c.kind!=='monster')throw Error('Carte Monstre invalide.');const need=tributeCount(c);if(need>p.field.filter(Boolean).length)throw Error(`Il faut ${need} Sacrifice(s).`);if(need){let n=0;for(let i=0;i<p.field.length&&n<need;i++)if(p.field[i]){p.grave.push(p.field[i].id);p.field[i]=null;n++}}p.hand.splice(handIndex,1);p.field[zone]={id:c.id,name:c.name,atk:c.atk,def:c.def,pos:faceDown?'DEF':'ATK',face:!faceDown,level:c.level};p.normalUsed=true;g.log.push(`${c.name} est invoqué.`)}
function changePos(g,zone){if(!phaseAllowed(g,'MAIN1')&&!phaseAllowed(g,'MAIN2'))throw Error('Phase principale requise.');const m=g.player.field[zone];if(!m)throw Error('Aucun monstre.');m.pos=m.pos==='ATK'?'DEF':'ATK';m.face=true}
function battle(g,zone,target){if(g.active!=='player'||g.phase!=='BATTLE')throw Error('Battle Phase requise.');if(g.firstTurn)throw Error('Pas de Battle au premier tour.');const a=g.player.field[zone];if(!a||!a.face||a.pos!=='ATK')throw Error('Attaquant invalide.');if(a.hasAttacked)throw Error('Ce monstre a déjà attaqué.');a.hasAttacked=true;const d=g.enemy.field[target];if(!d){g.enemy.lp-=a.atk;g.log.push(`${a.name} attaque directement.`)}else{const diff=a.atk-(d.pos==='ATK'?d.atk:d.def);if(diff>0){if(d.pos==='ATK')g.enemy.lp-=diff;g.enemy.grave.push(d.id);g.enemy.field[target]=null}else if(diff<0&&d.pos==='ATK'){g.player.lp+=diff;g.player.grave.push(a.id);g.player.field[zone]=null}else if(diff<0){g.player.lp+=diff}else{if(d.pos==='ATK'){g.player.grave.push(d.id);g.player.field[target]=null}g.player.grave.push(a.id);g.player.field[zone]=null}}if(g.enemy.lp<=0)g.winner='player';if(g.player.lp<=0)g.winner='enemy'}
function end(g){if(g.phase!=='END')throw Error('Phase de Fin requise.');while(g.player.hand.length>6)g.player.grave.push(g.player.hand.pop());advance(g)}
function ai(g){if(g.active!=='enemy'||g.winner)return;const e=g.enemy;if(g.phase==='DRAW')g.phase='STANDBY';if(g.phase==='STANDBY')g.phase='MAIN1';if(g.phase==='MAIN1'&&!e.normalUsed){const idx=e.hand.findIndex(id=>card(id)?.kind==='monster'&&tributeCount(card(id))===0);const z=e.field.findIndex(x=>!x);if(idx>=0&&z>=0){const c=card(e.hand[idx]);e.hand.splice(idx,1);e.field[z]={id:c.id,name:c.name,atk:c.atk,def:c.def,pos:'ATK',face:true};e.normalUsed=true}}if(g.phase==='MAIN1')g.phase='BATTLE';if(g.phase==='BATTLE'&&!g.firstTurn){for(let i=0;i<5;i++){const a=e.field[i];if(!a||a.pos!=='ATK')continue;const targets=g.player.field.map((m,j)=>m?j:-1).filter(j=>j>=0);if(targets.length){const t=targets[0],d=g.player.field[t];if(a.atk>d.atk){g.player.grave.push(d.id);g.player.field[t]=null}else{e.grave.push(a.id);e.field[i]=null}}else g.player.lp-=a.atk;if(g.player.lp<=0){g.winner='enemy';break}}}if(!g.winner){g.phase='END';end(g)}}
// Public/auth
app.get('/api/health',(req,res)=>res.json({ok:true,version:'4.0.0-v2',game:'King of Duel'}));
app.get('/api/cards',(req,res)=>res.json(CARDS));
app.get('/api/pnj',(req,res)=>res.json(PNJ));
app.get('/api/rules',(req,res)=>res.json({lp:8000,mainDeck:{min:40,max:60},extraDeck:{min:0,max:15},startingHand:5,monsterZones:5,spellTrapZones:5,maxHandEnd:6,phases:['DRAW','STANDBY','MAIN1','BATTLE','MAIN2','END'],firstPlayerNoBattle:true,normalSummonPerTurn:1,tribute:{level5to6:1,level7plus:2},tournaments:5,vipLevels:3}));
app.post('/api/auth/register',(req,res)=>{const username=String(req.body?.username||'').trim();const password=String(req.body?.password||'');if(!/^[a-zA-Z0-9_]{3,24}$/.test(username)||password.length<8)return res.status(400).json({error:'Identifiant 3-24 caractères et mot de passe de 8 caractères minimum.'});if(db.users.some(u=>u.username.toLowerCase()===username.toLowerCase()))return res.status(409).json({error:'Identifiant déjà utilisé.'});const u={id:uid(),username,role:'PLAYER',passwordHash:hashPassword(password),createdAt:new Date().toISOString()};db.users.push(u);db.cardsOwned[u.id]=starterCollection();saveDb();audit(username,'REGISTER',u.id,{});const t=issueSession(u.id);res.status(201).json({token:t,user:publicUser(u)})});
app.post('/api/auth/login',(req,res)=>{const u=db.users.find(x=>x.username===req.body?.username);if(!u||!verifyPassword(req.body?.password||'',u.passwordHash))return res.status(401).json({error:'Identifiants incorrects.'});const t=issueSession(u.id);res.json({token:t,user:publicUser(u)})});
app.post('/api/auth/logout',auth,(req,res)=>{sessions.delete(req.token);res.json({ok:true})});
app.get('/api/me',auth,(req,res)=>res.json({user:publicUser(req.user),permissions:req.permissions,collection:ownedCards(req.user).length,allCards:hasFakeAll(req.user)}));
// Player profile, collection and decks
app.get('/api/profile',auth,(req,res)=>res.json({user:publicUser(req.user),collection:ownedCards(req.user),decks:db.decks.filter(d=>d.userId===req.user.id),friends:db.friends.filter(f=>f.userA===req.user.id||f.userB===req.user.id),stats:req.user.stats||{duels:0,wins:0,losses:0}}));
app.get('/api/collection',auth,(req,res)=>res.json({cards:ownedCards(req.user).map(card),count:ownedCards(req.user).length,allCards:hasFakeAll(req.user)}));
app.post('/api/decks',auth,requirePerm('deck.manage'),(req,res)=>{const name=String(req.body?.name||'Deck sans nom').trim().slice(0,50);const cards=Array.isArray(req.body?.cards)?req.body.cards.map(String):[];const err=validateDeck(req.user,{cards});if(err)return res.status(400).json({error:err});const d={id:uid(),userId:req.user.id,name,cards,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};db.decks.push(d);saveDb();audit(req.user.username,'CREATE_DECK',d.id,{name});res.status(201).json(d)});
app.delete('/api/decks/:id',auth,requirePerm('deck.manage'),(req,res)=>{const i=db.decks.findIndex(d=>d.id===req.params.id&&d.userId===req.user.id);if(i<0)return res.status(404).json({error:'Deck introuvable'});const d=db.decks.splice(i,1)[0];saveDb();audit(req.user.username,'DELETE_DECK',d.id,{});res.json({ok:true})});
// Friends: relationship based authorization
app.post('/api/friends/:username',auth,requirePerm('friend.manage'),(req,res)=>{const target=db.users.find(u=>u.username===req.params.username);if(!target||target.id===req.user.id)return res.status(400).json({error:'Joueur invalide.'});if(db.friends.some(f=>(f.userA===req.user.id&&f.userB===target.id)||(f.userB===req.user.id&&f.userA===target.id)))return res.status(409).json({error:'Déjà ami.'});const f={id:uid(),userA:req.user.id,userB:target.id,status:'ACCEPTED',createdAt:new Date().toISOString()};db.friends.push(f);saveDb();audit(req.user.username,'ADD_FRIEND',f.id,{target:target.username});res.status(201).json(f)});
// Tournaments: exactly five standard slots, admins can enter all; top 5 rewards.
app.get('/api/tournaments',(req,res)=>res.json(db.tournaments.map(t=>({...t,entrants:db.tournamentEntries.filter(e=>e.tournamentId===t.id).length}))));
app.post('/api/tournaments/:id/join',auth,(req,res)=>{const t=db.tournaments.find(x=>x.id===req.params.id);if(!t)return res.status(404).json({error:'Tournoi introuvable'});if(!tournamentAccess(req.user,t))return res.status(403).json({error:'Votre niveau VIP ne permet pas cet accès.'});if(db.tournamentEntries.some(e=>e.tournamentId===t.id&&e.userId===req.user.id))return res.status(409).json({error:'Déjà inscrit.'});const e={id:uid(),tournamentId:t.id,userId:req.user.id,joinedAt:new Date().toISOString(),competitiveMode:true,adminPowersDisabled:hasFakeAll(req.user)};db.tournamentEntries.push(e);saveDb();audit(req.user.username,'JOIN_TOURNAMENT',t.id,{competitiveMode:true,adminPowersDisabled:e.adminPowersDisabled});res.json({ok:true,entry:e,tournament:t})});
// Admin
app.get('/api/admin/overview',auth,requirePerm('audit.view'),(req,res)=>res.json({user:publicUser(req.user),cards:CARDS.length,users:db.users.map(publicUser),roles:PERMS,tournaments:db.tournaments,audit:db.audit.slice(-100).reverse(),rewards:db.rewards}));
app.post('/api/admin/users',auth,requirePerm('users.manage'),(req,res)=>{const username=String(req.body?.username||'').trim();const password=String(req.body?.password||'');const role=req.body?.role||'PLAYER';if(!db.roles[role]||username.length<3||password.length<8)return res.status(400).json({error:'Utilisateur, rôle ou mot de passe invalide.'});if(db.users.some(u=>u.username===username))return res.status(409).json({error:'Utilisateur existant.'});const u={id:uid(),username,role,passwordHash:hashPassword(password),createdAt:new Date().toISOString()};db.users.push(u);db.cardsOwned[u.id]=starterCollection();saveDb();audit(req.user.username,'CREATE_USER',u.id,{username,role});res.status(201).json(publicUser(u))});
app.patch('/api/admin/users/:id/role',auth,requirePerm('roles.manage'),(req,res)=>{const u=db.users.find(x=>x.id===req.params.id);if(!u)return res.status(404).json({error:'Utilisateur introuvable'});const role=req.body?.role;if(!db.roles[role])return res.status(400).json({error:'Rôle invalide'});const old=u.role;u.role=role;saveDb();audit(req.user.username,'CHANGE_ROLE',u.id,{from:old,to:role});res.json(publicUser(u))});
app.get('/api/admin/cards',auth,requirePerm('cards.use.all'),(req,res)=>res.json(CARDS));
app.post('/api/admin/test-mode',auth,requirePerm('admin.test'),(req,res)=>{const enabled=req.body?.enabled!==false;audit(req.user.username,'ADMIN_TEST_MODE',req.user.id,{enabled});res.json({enabled,allCardsFree:true,competitiveUse:false})});
app.post('/api/admin/tournaments',auth,requirePerm('tournament.create'),(req,res)=>{if(db.tournaments.length>=5)return res.status(400).json({error:'Les 5 tournois officiels existent déjà.'});const t={id:uid(),slot:db.tournaments.length+1,name:String(req.body?.name||`Tournoi ${db.tournaments.length+1}`),vipRequired:Number(req.body?.vipRequired||0),rewardTop5:true,status:'OPEN',createdBy:req.user.username,createdAt:new Date().toISOString()};if(![0,1,2,3].includes(t.vipRequired))return res.status(400).json({error:'VIP requis invalide.'});db.tournaments.push(t);saveDb();audit(req.user.username,'CREATE_TOURNAMENT',t.id,t);res.status(201).json(t)});
app.post('/api/admin/tournaments/:id/join',auth,(req,res)=>{const t=db.tournaments.find(x=>x.id===req.params.id);if(!t)return res.status(404).json({error:'Tournoi introuvable'});if(!tournamentAccess(req.user,t))return res.status(403).json({error:'Tournoi non accessible.'});res.json({ok:true,competitiveMode:true,adminPowersDisabled:hasFakeAll(req.user)})});
app.post('/api/admin/rewards',auth,requirePerm('rewards.manage'),(req,res)=>{const tournamentId=req.body?.tournamentId;const userId=req.body?.userId;const rank=Number(req.body?.rank);if(!db.tournaments.some(t=>t.id===tournamentId)||!db.users.some(u=>u.id===userId)||rank<1||rank>5)return res.status(400).json({error:'Récompense invalide.'});const r={id:uid(),tournamentId,userId,rank,reward:String(req.body?.reward||`Récompense Top ${rank}`),createdAt:new Date().toISOString()};db.rewards.push(r);saveDb();audit(req.user.username,'GRANT_REWARD',r.id,r);res.status(201).json(r)});
app.get('/api/admin/audit',auth,requirePerm('audit.view'),(req,res)=>res.json(db.audit.slice(-500).reverse()));
// Game
app.post('/api/game',auth,(req,res)=>{const deck=db.decks.find(d=>d.userId===req.user.id&&d.id===req.body?.deckId);const g=newGame(req.body?.pnjId,deck?.cards);g.ownerId=req.user.id;games.set(g.id,g);req.user.stats=req.user.stats||{duels:0,wins:0,losses:0};req.user.stats.duels++;saveDb();res.json(pub(g))});
app.get('/api/game/:id',auth,(req,res)=>{const g=games.get(req.params.id);if(!g||g.ownerId!==req.user.id)return res.status(404).json({error:'Partie introuvable'});res.json(pub(g))});
app.post('/api/game/:id/action',auth,(req,res)=>{try{const g=games.get(req.params.id);if(!g||g.ownerId!==req.user.id)return res.status(404).json({error:'Partie introuvable'});if(g.winner)return res.status(400).json({error:'Duel terminé'});const a=req.body?.action;if(a==='advance')advance(g);else if(a==='summon')summon(g,req.body.handIndex,req.body.zone,!!req.body.faceDown);else if(a==='position')changePos(g,req.body.zone);else if(a==='battle')battle(g,req.body.zone,req.body.target);else if(a==='end')end(g);else throw Error('Action inconnue');if(g.active==='enemy'&&!g.winner)ai(g);if(g.winner){req.user.stats=req.user.stats||{duels:0,wins:0,losses:0};if(g.winner==='player')req.user.stats.wins++;else req.user.stats.losses++;saveDb()}res.json(pub(g))}catch(e){res.status(400).json({error:e.message})}});
app.use((req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
app.listen(PORT,()=>console.log(`King of Duel V2: http://127.0.0.1:${PORT}`));
